<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Etudiant_model extends CI_Model
{

    public $table = 'etudiant';
    public $id = 'idEtd';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idEtd,matriculeEtd,nomEtd,postnomEtd,prenomEtd,emailEtd,genreEtd,pwdEtd');
        $this->datatables->from('etudiant');
        //add this line for join
        //$this->datatables->join('table2', 'etudiant.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('etudiant/read/$1'),'Read')." | ".anchor(site_url('etudiant/update/$1'),'Update')." | ".anchor(site_url('etudiant/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idEtd');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idEtd', $q);
	$this->db->or_like('matriculeEtd', $q);
	$this->db->or_like('nomEtd', $q);
	$this->db->or_like('postnomEtd', $q);
	$this->db->or_like('prenomEtd', $q);
	$this->db->or_like('emailEtd', $q);
	$this->db->or_like('genreEtd', $q);
	$this->db->or_like('pwdEtd', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idEtd', $q);
	$this->db->or_like('matriculeEtd', $q);
	$this->db->or_like('nomEtd', $q);
	$this->db->or_like('postnomEtd', $q);
	$this->db->or_like('prenomEtd', $q);
	$this->db->or_like('emailEtd', $q);
	$this->db->or_like('genreEtd', $q);
	$this->db->or_like('pwdEtd', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Etudiant_model.php */
/* Location: ./application/models/Etudiant_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-14 11:45:34 */
/* http://harviacode.com */