<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Professeurs_model extends CI_Model
{

    public $table = 'professeurs';
    public $id = 'idProf';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idProf,matriculeProf,nomProf,postnomProf,prenomProf,emailProf');
        $this->datatables->from('professeurs');
        //add this line for join
        //$this->datatables->join('table2', 'professeurs.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('professeurs/read/$1'),'Read')." | ".anchor(site_url('professeurs/update/$1'),'Update')." | ".anchor(site_url('professeurs/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idProf');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idProf', $q);
	$this->db->or_like('matriculeProf', $q);
	$this->db->or_like('nomProf', $q);
	$this->db->or_like('postnomProf', $q);
	$this->db->or_like('prenomProf', $q);
	$this->db->or_like('emailProf', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idProf', $q);
	$this->db->or_like('matriculeProf', $q);
	$this->db->or_like('nomProf', $q);
	$this->db->or_like('postnomProf', $q);
	$this->db->or_like('prenomProf', $q);
	$this->db->or_like('emailProf', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Professeurs_model.php */
/* Location: ./application/models/Professeurs_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-14 11:45:34 */
/* http://harviacode.com */