<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Resultat_cours_model extends CI_Model
{

    public $table = 'resultat_cours';
    public $id = 'idRc';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idRc', $q);
	$this->db->or_like('idCe', $q);
	$this->db->or_like('idEtd', $q);
	$this->db->or_like('td', $q);
	$this->db->or_like('tp', $q);
	$this->db->or_like('interro', $q);
	$this->db->or_like('examen', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idRc', $q);
	$this->db->or_like('idCe', $q);
	$this->db->or_like('idEtd', $q);
	$this->db->or_like('td', $q);
	$this->db->or_like('tp', $q);
	$this->db->or_like('interro', $q);
	$this->db->or_like('examen', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Resultat_cours_model.php */
/* Location: ./application/models/Resultat_cours_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-12 18:48:03 */
/* http://harviacode.com */